package com.amich.provider.model;


import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.HashSet;
import java.util.Set;

@Data
public class Address {
    private Long id;

    private String googleMapAddress;

    private boolean enabled = false;

    @EqualsAndHashCode.Exclude
    private Set<Provider> providers = new HashSet<>();

    public Address() {
    }

    public Address(String googleMapAddress, boolean enabled) {
        this.googleMapAddress = googleMapAddress;
        this.enabled = enabled;
    }

    // Getters and setters are generated by Lombok
}
