package com.amich.provider.model;

import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.HashSet;
import java.util.Set;

@Data
public class Service {
    private Long id;

    private String serviceName;

    private String description;

    private com.amich.provider.model.MeasureUnit measureUnit;

    private Service serviceParent;

    @EqualsAndHashCode.Exclude
    private Set<Service> subServices = new HashSet<>();

    public Service() {
    }

    public Service(String serviceName, String description, MeasureUnit measureUnit) {
        this.serviceName = serviceName;
        this.description = description;
        this.measureUnit = measureUnit;
    }

    // Getters and setters are generated by Lombok


}

